### ISSUE TITLE
Example code recently broken

### ISSUE THREAD

**Issue by bbobrian** [evansiroky/gtfs-sequelize#28]
Everything worked perfectly a few weeks ago, but if I clone the current repo and use the example code, it fails miserably.  It seems like there is something odd happening with the async lib.

**Comment by evansiroky** [comment]
What version of node.js and npm are you using?

**Comment by bbobrian** [comment]
node: 6.3.1
npm: 3.10.3

**Comment by evansiroky** [comment]
Confirmed not working with node 6.  Will fix when I have time.  Feel free to submit a pull request if you find a solution.

**Comment by evansiroky** [comment]
This appears to have been fixed by some dependency update.  Please re-open if this is not the case.
