### ISSUE TITLE
set current_schema option

### ISSUE THREAD

**Issue by sign0** [evansiroky/gtfs-sequelize#31]
Hi Evan,
I would like to configure a specific schema to import GTFS. I tried this postgres url connection string, but without success: 'postgres://username:password@localhost:5432/gtfs?current_schema=test'.

Do you have an idea to reach my goals?
ps: this would be very helpful for everyone to be able to have several gtfs in the same database without conflicts.

Currently, I import everything into the public schema and at the end of the import I rename this schema then I recreate a public schema for my future imports. But I guess there's a best way to do it ! :)

Thanks !

**Comment by evansiroky** [comment]
Looks like this needs to be included in the model definition of each Sequelize table definition ([See docs](http://docs.sequelizejs.com/en/v3/api/sequelize/#definemodelname-attributes-options-model)).  Will try to work on this soon.
