### ISSUE TITLE
Issues loading on first setup

### ISSUE THREAD

**Issue by Aghassi** [evansiroky/gtfs-sequelize#54]
Hello!

I've been trying to follow the `README` to get this working locally before trying it in prod, but I can't seem to get my data to load into the database at all. So far, my code looks like this:

```javascript
var GTFS = require('gtfs-sequelize');

var downloadConfig = {
  gtfsUrl: 'http://transitfeeds.com/p/nj-transit/409/latest/download',
  downloadsDir: 'downloads'
};

var gtfs = GTFS(downloadConfig);
gtfs.downloadGtfs(function() {
  //download has finished callback
  console.log("Download complete, adding gtfs to database.");
  var pgConfig = {
    database: 'postgres://gtfs_sequelize:gtfs_sequelize@localhost:5432/gtfs-sequelize-test',
    downloadsDir: 'downloads',
    gtfsFilename: 'gtfs.zip',
    sequelizeOptions: {
      logging: false
    }
  };

  var gtfs = GTFS(pgConfig);
  gtfs.loadGtfs(function() {
    //database loading has finished callback
    console.log("Finished loading to database");
  });
});
```

However, I keep receiving the following error: 
```javascript
path.js:7
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```

What exactly am I doing wrong here? I'm using node version `lts/boron` if that helps.

**Comment by evansiroky** [comment]
Thanks for reporting.

Unfortunately a lot is going on here that is the fault of this library.

1.  The README docs are wrong and need to be updated.  The config option `gtfsFilename` should be `gtfsFileOrFolder`.
1.  The url you are querying does a redirect to the actual file, which this library doesn't yet support
1.  The url it redirects to downloads via https, which this library can't handle
1.  This particular feed is the kind that omits the calendar.txt file and instead includes everything in calendar_dates.txt.  This library also can't handle that, but at least that is a know issue (#53)

I should probably work on fixes for all these things, but it's low priority for me at the moment.  If you want to take a shot at it I'm happy to accept a PR.

**Comment by evansiroky** [comment]
These issues should be fixed now.
